version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: crawl_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-crawl_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-crawl_password}
      POSTGRES_DB: ${POSTGRES_DB:-crawl_db}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "${HOST_POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crawl_user -d crawl_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - crawl_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: crawl_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - postgres
    networks:
      - crawl_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: crawl_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-crawler}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-crawler_password}
    ports:
      - "${HOST_RABBITMQ_PORT:-5672}:5672"
      - "${HOST_RABBITMQ_MGMT_PORT:-15672}:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - crawl_network

  test_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crawl_test_app
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://crawl_user:crawl_password@postgres:5432/crawl_db}
      CRAWLER_DATABASE_URL: ${CRAWLER_DATABASE_URL:-postgresql://crawl_user:crawl_password@postgres:5432/crawl_db}
      CRAWLER_CELERY_BROKER_URL: ${CRAWLER_CELERY_BROKER_URL:-amqp://crawler:crawler_password@rabbitmq:5672//}
      CRAWLER_CELERY_RESULT_BACKEND: ${CRAWLER_CELERY_RESULT_BACKEND:-db+postgresql://crawl_user:crawl_password@postgres:5432/crawl_db}
      CRAWLER_CELERY_TASK_ALWAYS_EAGER: ${CRAWLER_CELERY_TASK_ALWAYS_EAGER:-False}
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./:/app
      - ${TEST_APP_STORAGE_MOUNT_PATH:-./storage}:/app/storage
      - ${TEST_APP_DATA_MOUNT_PATH:-./data}:/app/data
    command: python test_models.py
    networks:
      - crawl_network

volumes:
  postgres_data:
  pgadmin_data:
  rabbitmq_data:

networks:
  crawl_network:
    driver: bridge
