#!/bin/sh
set -euo pipefail

CONFIG_DIR=${PGBOUNCER_CONFIG_DIR:-/etc/pgbouncer}
LOG_DIR=${PGBOUNCER_LOG_DIR:-/var/log/pgbouncer}

POSTGRES_HOST=${POSTGRES_HOST:-postgres}
POSTGRES_PORT=${POSTGRES_PORT:-5432}
POSTGRES_DB=${POSTGRES_DB:-crawl_db}
POSTGRES_USER=${POSTGRES_USER:-crawl_user}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-crawl_password}

PGBOUNCER_LISTEN_ADDR=${PGBOUNCER_LISTEN_ADDR:-0.0.0.0}
PGBOUNCER_PORT=${PGBOUNCER_PORT:-6432}
PGBOUNCER_POOL_MODE=${PGBOUNCER_POOL_MODE:-transaction}
PGBOUNCER_MAX_CLIENT_CONN=${PGBOUNCER_MAX_CLIENT_CONN:-200}
PGBOUNCER_DEFAULT_POOL_SIZE=${PGBOUNCER_DEFAULT_POOL_SIZE:-20}
PGBOUNCER_RESERVE_POOL_SIZE=${PGBOUNCER_RESERVE_POOL_SIZE:-5}
PGBOUNCER_RESERVE_POOL_TIMEOUT=${PGBOUNCER_RESERVE_POOL_TIMEOUT:-5}
PGBOUNCER_SERVER_LIFETIME=${PGBOUNCER_SERVER_LIFETIME:-900}
PGBOUNCER_SERVER_IDLE_TIMEOUT=${PGBOUNCER_SERVER_IDLE_TIMEOUT:-300}
PGBOUNCER_STATS_PERIOD=${PGBOUNCER_STATS_PERIOD:-60}
PGBOUNCER_AUTH_TYPE=${PGBOUNCER_AUTH_TYPE:-plain}
PGBOUNCER_IGNORE_STARTUP_PARAMETERS=${PGBOUNCER_IGNORE_STARTUP_PARAMETERS:-extra_float_digits}

ADMIN_USERS=${PGBOUNCER_ADMIN_USERS:-postgres,${POSTGRES_USER}}
STATS_USERS=${PGBOUNCER_STATS_USERS:-${POSTGRES_USER}}

mkdir -p "$CONFIG_DIR" "$LOG_DIR"

CONFIG_FILE="$CONFIG_DIR/pgbouncer.ini"
AUTH_FILE="$CONFIG_DIR/userlist.txt"

cat >"$CONFIG_FILE" <<EOF
[databases]
${POSTGRES_DB} = host=${POSTGRES_HOST} port=${POSTGRES_PORT} dbname=${POSTGRES_DB}

[pgbouncer]
listen_addr = ${PGBOUNCER_LISTEN_ADDR}
listen_port = ${PGBOUNCER_PORT}
auth_type = ${PGBOUNCER_AUTH_TYPE}
auth_file = ${AUTH_FILE}
admin_users = ${ADMIN_USERS}
stats_users = ${STATS_USERS}
pool_mode = ${PGBOUNCER_POOL_MODE}
max_client_conn = ${PGBOUNCER_MAX_CLIENT_CONN}
default_pool_size = ${PGBOUNCER_DEFAULT_POOL_SIZE}
reserve_pool_size = ${PGBOUNCER_RESERVE_POOL_SIZE}
reserve_pool_timeout = ${PGBOUNCER_RESERVE_POOL_TIMEOUT}
server_reset_query = DISCARD ALL
server_lifetime = ${PGBOUNCER_SERVER_LIFETIME}
server_idle_timeout = ${PGBOUNCER_SERVER_IDLE_TIMEOUT}
stats_period = ${PGBOUNCER_STATS_PERIOD}
ignore_startup_parameters = ${PGBOUNCER_IGNORE_STARTUP_PARAMETERS}
logfile = ${LOG_DIR}/pgbouncer.log
pidfile = ${CONFIG_DIR}/pgbouncer.pid
unix_socket_dir = ${CONFIG_DIR}
EOF

cat >"$AUTH_FILE" <<EOF
"${POSTGRES_USER}" "${POSTGRES_PASSWORD}"
EOF

chmod 600 "$AUTH_FILE"

if [ "${1:-}" = "pgbouncer" ]; then
  shift
fi

if [ "$(id -u)" = "0" ]; then
  chown -R pgbouncer:pgbouncer "$CONFIG_DIR" "$LOG_DIR"
  exec su-exec pgbouncer pgbouncer "$CONFIG_FILE" "$@"
fi

exec pgbouncer "$CONFIG_FILE" "$@"
